// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/vaidik-bajpai/medibridge/internal/models"
)

// SessionStorer is an autogenerated mock type for the SessionStorer type
type SessionStorer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *SessionStorer) Create(_a0 context.Context, _a1 *dto.CreateSessReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateSessReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserByToken provides a mock function with given fields: ctx, token
func (_m *SessionStorer) FindUserByToken(ctx context.Context, token string) (*dto.UserModel, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByToken")
	}

	var r0 *dto.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.UserModel, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.UserModel); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSessionStorer creates a new instance of SessionStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStorer {
	mock := &SessionStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
