basePath: /
host: localhost:8080
info:
  contact:
    email: support@medibridge.com
    name: API Support
  description: This is the API documentation for the MediBridge backend.
  termsOfService: http://example.com/terms/
  title: MediBridge API
  version: "1.0"
paths: {}
swagger: "2.0"
